config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  devise_for :users

  root to: 'projects#index'
  resources :projects do
    member do
      get    'assign_developer'
      get    'assign_sqa'
      get    'add_developer'
      delete 'remove_developer'
      post   'add_sqa'
      delete 'remove_sqa'
    end
  end

  resources :bugs do
    member do
      patch 'update_status'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_one_attached :screen_shot

  validates :title, :severity, :actual_result, :expected_result, presence: true

  enum severity: %i[critical high medium low]
  enum status: %i[start in_progress ready_for_testing testing_in_progress qa_approved done] do
    event :bug_state do
      transition start: :in_progress
      transition in_progress: :ready_for_testing
      transition ready_for_testing: :testing_in_progress
      transition testing_in_progress: :qa_approved
      transition qa_approved: :done
      transition done: :start
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :manager, class_name: 'User'
  has_many :project_users
  has_many :users, through: :project_users
  has_many :bugs

  validates :name, presence: true
end

app/models/project_user.rb
class ProjectUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: %i[admin manager developer sqa]

  has_many :created_projects, class_name: 'Project', foreign_key: 'manager_id'
  has_many :project_users
  has_many :projects, through: :project_users
  has_many :bugs
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :role, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :role, :email, :password, :avatar) }
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = policy_scope(Bug)
  end

  def new
    @bugs = Bug.new
    @user = current_user
    @projects = @user.projects
    if params[:project_id].present?
      @developers = Project.find(params[:project_id]).users.developer
    else
      @developers = User.developer
    end
    if request.xhr?
      respond_to do |format|
        format.json do
          render json: { developers: @developers }
        end
      end
    end
  end

  def create
    @bug = Bug.new(bug_params)
    redirect_to bugs_path if @bug.save
  end

  def edit
    @bug = Bug.find(params[:id])
    @user = current_user
    @projects = @user.projects
    @users = User.developer
  end

  def update
    @bug = Bug.find(params[:id])
    redirect_to root_path if @bug.update_attributes(bug_params)
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    redirect_to root_path if @bug.destroy
  end

  def update_status
    @bug = Bug.find(params[:id])
    @bug.bug_state
    redirect_back fallback_location: bugs_path
  end

  private

  def bug_params
    params.require(:bug).permit(:project_id, :title, :severity, :actual_result, :expected_result, :user_id, :screen_shot)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = policy_scope(Project)
  end

  def new
    @project  = Project.new
    authorize @project
    @managers = User.manager
  end

  def create
    @project = Project.new(project_params)
    redirect_to root_path if @project.save
  end

  def show
    @project = Project.find(params[:id])
    authorize @project
  end

  def edit
    @project = Project.find(params[:id])
    authorize @project
    @managers = User.manager
  end

  def update
    @project = Project.find(params[:id])
    redirect_to root_path if @project.update_attributes(project_params)
  end

  def destroy
    @project = Project.find(params[:id])
    authorize @project
    @project.destroy
    redirect_to root_path if @project.destroy
  end

  def assign_developer
    @developers = User.developer
    @project = Project.find(params[:id])
    authorize @project
    @project_user = @project.users
  end

  def add_developer
    @project = Project.find(params[:id])
    @project.users << User.find(params[:user_id])

    redirect_back fallback_location: root_path
  end

  def remove_developer
    @project = Project.find(params[:id])
    @user = User.find(params[:user_id])
    @project.users.destroy(@user)

    redirect_back fallback_location: root_path
  end

  def assign_sqa
    @sqa = User.sqa
    @project = Project.find(params[:id])
    authorize @project
    @project_user = @project.users
  end

  def add_sqa
    @project = Project.find(params[:id])
    @project.users << User.find(params[:user_id])

    redirect_back fallback_location: root_path
  end

  def remove_sqa
    @project = Project.find(params[:id])
    @user = User.find(params[:user_id])
    @project.users.destroy(@user)

    redirect_back fallback_location: root_path
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :manager_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user, size = 40)
    if user.avatar.attached?
      user.avatar.variant(resize: "#{size}x#{size}!")
    else
      gravatar_image_url(user.email, size: size)
    end
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/bugs/edit.html.erb
<div class="col-md-4 offset-4">
  <h1>Create New Bug</h1>
</div>

<%= form_for @bug, html: { multipart: true } do |f| %>
  <div class="form-group">
    <div class="form-group">
      <div class="col-md-4 offset-4">
      <%= f.label :project_id, 'Select Project', class: 'control-label'%><br>
      <%= f.select :project_id, @projects.collect {|p| [ p.name, p.id ]}, { :selected => @bug.project_id }, {class: 'form-control', required: true} %>
      </div>
    </div>

    <div class="col-lg-4 offset-4 dropdown">
      <%= f.label :name, 'Title'%>
      <%= f.text_field :title, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :severity, 'Severity', class: 'control-label'%><br>
      <%= f.radio_button :severity, 'critical', {required: true} %> Critical <br />
      <%= f.radio_button :severity, 'high', {required: true} %> High <br />
      <%= f.radio_button :severity, 'medium', {required: true} %> Medium <br />
      <%= f.radio_button :severity, 'low', {required: true} %> low <br />
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :actual_result, 'Actual Result'%>
      <%= f.text_area :actual_result, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :expected_result, 'Expected Result'%>
      <%= f.text_area :expected_result, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :screen_shot, 'Upload Bug Image'%> <br />
      <% if @bug.screen_shot.present?%>
        <%= image_tag @bug.screen_shot.url(:thumb) %><br/>
      <% end %>
      <%= f.file_field :screen_shot%>
    </div>
  </div>

  <div class="form-group">
      <div class="col-md-4 offset-4">
      <%= f.label :user_id, 'Assign To', class: 'control-label'%><br>
      <%= f.select :user_id, @users.collect {|p| [ p.name, p.id ]}, { :selected => @bug.user_id }, {class: 'form-control', required: true} %>
      </div>
    </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.submit 'Update Bug', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/bugs/index.html.erb
<div class= 'container'>
  <div class="row">
    <h2 class="mt-3">Bugs Dashboard</h2>
    <table id="example" class="table table-striped table-bordered mt-4">
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Bug Title</th>
          <th>Bug Severity</th>
          <th>Actual Result</th>
          <th>Expected Result</th>
          <th>Screen Shot</th>
          <th>Assign To</th>
          <th>Status</th>
          <% if current_user.sqa? %>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @bugs.each do |b| %>
          <tr>
            <td> <%= b.project.name %> </td>
            <td> <%= b.title.capitalize %> </td>
            <td> <%= b.severity.capitalize %> </td>
            <td> <%= b.actual_result.capitalize %> </td>
            <td> <%= b.expected_result.capitalize %> </td>
            <td>
                <%=link_to b.screen_shot, class: 'fancybox' do %>
                  <%= image_tag(b.screen_shot.variant(resize: "40x40"))  %>
                <% end %>
            </td>
            <td> <%= b.user.name %> </td>
            <% if current_user.sqa? %>
            <td>
              <%= link_to 'Edit', edit_bug_path(b.id) %>
              <%= link_to 'Delete', bug_path(b.id), method: :delete, data: {:confirm => "Are you sure to want to delete this bug?" } %>
            </td>
            <% end %>
            <td> <%= link_to b.status, update_status_bug_path(b.id), method: :patch, class: 'btn btn-primary' %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/bugs/new.html.erb
<div class="col-md-4 offset-4">
  <h1>Create New Bug</h1>
</div>

<%= form_for @bugs, html: { multipart: true } do |f| %>
  <div class="form-group">
    <div class="form-group">
      <div class="col-md-4 offset-4">
      <%= f.label :project_id, 'Select Project', class: 'control-label'%><br>
      <%= f.select :project_id, options_from_collection_for_select(@projects, :id, :name), {include_blank: true}, {class: 'form-control', required: true} %>
      </div>
    </div>

    <div class="col-lg-4 offset-4">
      <%= f.label :name, 'Title'%>
      <%= f.text_field :title, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :severity, 'Severity', class: 'control-label'%><br>
      <%= f.radio_button :severity, 'critical', {required: true} %> Critical <br />
      <%= f.radio_button :severity, 'high', {required: true} %> High <br />
      <%= f.radio_button :severity, 'medium', {required: true} %> Medium <br />
      <%= f.radio_button :severity, 'low', {required: true} %> low <br />
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :actual_result, 'Actual Result'%>
      <%= f.text_area :actual_result, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :expected_result, 'Expected Result'%>
      <%= f.text_area :expected_result, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :screen_shot, 'Upload Bug Image'%> <br />
      <%= f.file_field :screen_shot, :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :user_id, 'Assign To'%>
      <%= f.select :user_id, options_from_collection_for_select(@developers, :id, :name), {}, {class: 'form-control', required: true, disabled: ''} %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.submit 'Add Bug', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bugzila</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
    <script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href=" https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <%= link_to('Bugzila', root_path, :class => "navbar-brand")%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <%= link_to('People', user_index_path, :class => "nav-link dropdown-item")%>
          </ul>
          <ul class="navbar-nav ">
            <li class="nav-item dropdown justify-content-end">
              <%= link_to root_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
                <%= image_tag user_avatar(current_user, 40), class: "rounded-circle" %>
                <%= current_user.name %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to('Edit Profile', edit_user_registration_path, :class => "nav-link dropdown-item")%>
                <div class="dropdown-divider"></div>
                  <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "nav-link dropdown-item")%>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/projects/assign_developer.html.erb
<div class= 'container'>
  <div class="row">
    <h2 class="mt-3 text-muted"> Assign Developer </h2>
    <table id="example" class="table table-striped table-bordered mt-2">
      <thead>
        <tr>
          <th>Developer Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
         <% @developers.each do |d| %>
          <tr>
            <td> <%= d.name %> </td>
            <td>
              <% if @project_user.exists?(d.id) %>
                <%= link_to "Remove Developer", remove_developer_project_path(user_id: d.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %>
              <% else %>
                <%= link_to "Add Developer", add_developer_project_path(user_id: d.id), method: 'get', class: 'btn btn-success btn-sm' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/projects/assign_sqa.html.erb
<div class= 'container'>
  <div class="row">
    <h2 class="mt-3 text-muted"> Assign Sqa </h2>
    <table id="example" class="table table-striped table-bordered mt-2">
      <thead>
        <tr>
          <th>Developer Name</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
         <% @sqa.each do |s| %>
          <tr>
            <td> <%= s.name %> </td>
             <td>
              <% if @project_user.exists?(s.id) %>
                <%= link_to "Remove Sqa", remove_sqa_project_path(user_id: s.id), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-danger btn-sm' %>
              <% else %>
                <%= link_to "Add Sqa", add_sqa_project_path(user_id: s.id), method: 'post', class: 'btn btn-success btn-sm' %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Back", :back %>
  </div>
</div>

app/views/projects/edit.html.erb
<div class="col-md-4 offset-4">
  <h1>Update Project</h1>
</div>

<%= form_for @project do |f| %>
  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :name, 'Project Name'%>
      <%= f.text_field :name, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :description, 'Project Description'%>
      <%= f.text_area :description, autofocus: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :manager, 'Project Manager', class: 'control-label'%><br>
      <%= f.select :manager_id, @managers.collect {|p| [ p.name, p.id ]}, { :selected => @project.manager_id }, { class: 'form-control'} %>
    </div>
  </div>

   <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.submit 'Update Project', class: 'btn btn-primary' %> <br>
      <%= link_to "Back", :back %>
    </div>
  </div>
<% end %>

app/views/projects/index.html.erb
<div class= 'container'>
  <div class="row">
    <% if current_user.admin? || current_user.manager? %>
      <a href= "projects/new" role="button" class="btn btn-primary btn-md mt-3">Create Project</a>
    <% end %>
    <% if current_user.sqa? %>
      <a href= "bugs/new" role="button" class="btn btn-primary btn-md mt-3">Create Bug</a>
    <% end %>
      <a href= "bugs" role="button" class="btn btn-primary btn-md mt-3 ml-3">Bugs Dashboard</a>
    <table id="example" class="table table-striped table-bordered mt-3">
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Project Description</th>
          <th>Assign Manager</th>
          <% if current_user.admin? || current_user.manager?%>
            <th>Actions</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td> <%= project.name %> </td>
            <td> <%= project.description %> </td>
            <td> <%= project.manager.name %> </td>
            <% if policy(project).update? %>
              <td>
                <%= link_to 'Show', project_path(project) %>
                <%= link_to 'Edit', edit_project_path(project) %>
                <%= link_to 'Delete', project_path(project), method: :delete, data: {:confirm => "Are you sure to want to delete this project?" } %>
              </td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="col-md-4 offset-4">
  <h1>Create New Project</h1>
</div>

<%= form_for @project do |f| %>
  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :name, 'Project Name'%>
      <%= f.text_field :name, autofocus: true, class: 'form-control', :required => true %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4 dropdown">
      <%= f.label :description, 'Project Description'%>
      <%= f.text_area :description, autofocus: true, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.label :manager, 'Project Manager', class: 'control-label'%><br>
      <%= f.select :manager_id, options_from_collection_for_select(@managers, :id, :name), {include_blank: true}, {class: 'form-control', required: true} %>
    </div>
  </div>

   <div class="form-group">
    <div class="col-md-4 offset-4">
      <%= f.submit 'Add Project', class: 'btn btn-primary' %><br>
      <%= link_to "Back", :back %>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<div class= 'container'>
  <div class="row">
    <table id="example" class="table table-striped table-bordered mt-5">
      <thead>
        <tr>
          <th>Project Name</th>
          <th>Project Description</th>
          <th>Assign Manager</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td> <%= @project.name %> </td>
            <td> <%= @project.description %> </td>
            <td> <%= @project.manager.name %> </td>
            <td>
              <%= link_to "Assign Developer", assign_developer_project_path, class: 'btn btn-primary' %>
              <%= link_to "Assign Sqa", assign_sqa_project_path, class: 'btn btn-secondary' %>
            </td>
          </tr>
      </tbody>
    </table>
     <%= link_to "Back", :back %>
  </div>
</div>

app/views/user/index.html.erb
<div class= 'container'>
  <div class="row">
    <table id="example" class="table table-striped table-bordered mt-3">
      <thead>
        <tr>
          <th>User Name</th>
          <th>User Role</th>
          <th>User Email</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
          <tr>
            <td> <%= u.name %> </td>
            <td> <%= u.role %> </td>
            <td> <%= u.email %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>